### ISSUE TITLE
Review Inventory Status Page and Dispense Form

### ISSUE THREAD

**Issue by glarita** [minerva-medical/minerva#18]
## Review Branch

* [review-18](https://github.com/minerva-medical/minerva/tree/review-18)

## Files to be Reviewed

* [Dispense.jsx](https://github.com/minerva-medical/minerva/blob/issue-10/app/imports/ui/pages/Dispense.jsx)  
* [Status.jsx](https://github.com/minerva-medical/minerva/blob/issue-9/app/imports/ui/pages/Status.jsx)

## Checklists

* [Architecture](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-architecture-checklist)
* [Design](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-design-checklist)
* [JS](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-js-checklist)
* [React](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-react-checklist)
* [UI](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-ui-checklist)

## Specific Requests for this request 

Currently these are mockups, but I find that these two pages are probably the two most important pages in the application. 

Does the code for the dispense page make sense to you? Is there another way that you can think of making this code cleaner if possible?

Does the code for the status page make sense to you? Is there another way that you can think of making this code cleaner if possible?

## Due Date 

12:00 pm Tuesday, September 14 2021

**Comment by cammoore** [comment]
## Dispense.jsx

L1: ESLint - indentation.

RE-09: Prefer functions
https://github.com/minerva-medical/minerva/blob/979f0b9d5db0eac7e7e96bdeccd8faba04ecfdae/app/imports/ui/pages/Dispense.jsx#L14

L99 - 185: Use Uniforms.

RE-06: Define constants in withTracker

## Status.jsx

RE-09: Prefer functions.

L19 - 28: Consolidate the state to common object to share with
Dispense.jsx. 

L30 - 40: Consolidate the options to share with Dispanse.jsx.

RE-06: Define constants in withTracker

Think about sub-components and sharing state/properties.

**Comment by jnocampo** [comment]
Dispense: 

    Architecture: 
        AR-01: 
        - Yes
        - No, file should be dispense not Dispense, file is currently in PascalCase 

        AR-02:
        - Yes

        AR-03:
        - Yes

    Design: 

        DE-01: 
        - No need to refactor

        DE-02:
        - No

        DE-03:
        - No

        DE-04:
        - No

        DE-05: 
        - No & no immediate imporvements needed for base form templates. Any other design is not yet necessary in this stage. 

        DE-06:
        - Yes, code is readable

        DE-07:
        - Will not be repeated

        DE-08:
        - Lines 17-74 is similar to status page of lines 17-70
        - Defined constants with tracker similar to status

    JavaScript & ESLINT: 
        JS-01: 
        - Names are formated appropriately 

        JS-02:
        - Spread operator not necessary 

        JS-03:
        - No we don't need it 

        JS-04:
        - Arrow functions are used as necessary 

        JS-05:
        - underscore is used. Map and Pluck functions are present in file

        JS-06:
        - Console.log on line 64

        JS-07:
        - Line 3 jsdoc is not used, use of '//' not '/**'

        ES-01:
        - indentation error on line 1
         
        ES-02: 
        - No 

    React:
        RE-01:
        - Component as is, is fine

        RE-02:
        - State is not in loop 

        RE-03:
        - default export not changed

        RE-04:
        - code is fine

        RE-05: 
        There is no RE-05 on the site. skips from 4 to 6

        RE-06:
        - constants are defined in withTracker

        RE-07:
        - code is fine 

        RE-08:
        - imported component names and files match

        RE-09:
        - There is use of state function in compoent to dispense items

        RE-10:
        - No card or widget in names

    UI:
        UI-01:
        - Create medication/vaccine dispense form. 
        - Yes, it does what it is supposed to do

        UI-02:
        - layout is fine for now, not all screen sizes are yet to be accounted for

        UI-03:
        - Links, controllers, buttons are fine

        UI-04:
        - Forms are fine

        UI-05:
        - information requesting is clear

        UI-06:
        - Page loads fine

        UI-07:
        - no errors generated

Status:

    Architecture: 
        AR-01: 
        - Yes
        - No, file should be status not Status, file is currently in PascalCase 

        AR-02:
        - Yes

        AR-03:
        - Yes

    Design: 

        DE-01: 
        - No need to refactor

        DE-02:
        - No

        DE-03:
        - No

        DE-04:
        - No

        DE-05: 
        - No & no immediate imporvements needed for base form templates. Any other design is not yet necessary in this stage. 

        DE-06:
        - Yes, code is readable

        DE-07:
        - Possibly, referencing DE-08, some can be reused for a possible dashboard page. 

        DE-08:
        - Some items can be reused. If we create home page dashboard, we can possibly display items that are immediately low, i.e. dashboard basic reports. 
        - Lines 17-70 is similar to dispense page of lines 17-74
        - Defined constants with tracker similar to dispense

    JavaScript & ESLINT: 
        JS-01: 
        - Names are formated appropriately 

        JS-02:
        - Spread operator not necessary 

        JS-03:
        - No we don't need it 

        JS-04:
        - Arrow functions are used as necessary 

        JS-05:
        - underscore is used. Map and Pluck functions are present in file

        JS-06:
        - Console.log on line 59

        JS-07:
        - Line 3 jsdoc is not used, use of '//' not '/**'

        ES-01:
        - no eslint errors
        - No 

        ES-02:
        - Not needed

    React:
        RE-01:
        - Component as is, is fine

        RE-02:
        - State is not in loop 

        RE-03:
        - default export not changed

        RE-04:
        - code is fine

        RE-05: 
        There is no RE-05 on the site. skips from 4 to 6

        RE-06:
        - constants are defined in withTracker

        RE-07:
        - code is fine 

        RE-08:
        - imported component names and files match

        RE-09:
        - Fine

        RE-10:
        - No card or widget in names

    UI:
        UI-01:
        - Display inventory status of medication 
        - Yes, it does what it is supposed to do

        UI-02:
        - layout is fine for now, not all screen sizes are yet to be accounted for

        UI-03:
        - Links, controllers, buttons are fine

        UI-04:
        - Forms are fine

        UI-05:
        - information is clear

        UI-06:
        - Page loads fine
        
        UI-07:
        - no errors generated

**Comment by glarita** [comment]
##ICS 414 Review Issue 18

## Dispense.jsx

### Architecture

- Checklist met

### Design

- DE-03: Line 3: Is swal still needed? If  not then we can remove.
- Line 63-70 getOptions is not used on this page

### Javascript

- JS-06: Console.log present. Should we use a swal instead to provide alert to user?

### React

- Checklist met

### UI 

- UI-02: May need to check if compatible with mobile devices (change grid/segment) Although I am not sure if this is applicable since the client will only use the application on laptops. 


## Status.jsx

### Architecture

- Checklist met

### Design

- DE-03: Line 4 Is swall needed?

### Javascript

- JS-06: Line 59 console.log present.

### React

- Checklist met

### UI 

- UI-02" May need to check if compatible with mobile devices. Although I am not sure if this is necessary for our client.

**Comment by alyssandra-cabading** [comment]
Dispense.jsx

L1: Minor issue — fix "import" spacing.
L26, 50, 51, 109, 110: Would it make more sense to name it "dispensedBy" than "dispensedFrom", considering it references the user.
L64: JS-06: Avoid console.logs.
L69: JS-05: Avoid underscore.
L101: DE-05: This comment can be omitted.
L191: Change "Stuff" to reflect "Dispense" in the comment.


Status.jsx

L16 to L41: DE-01: Can we refactor to reduce duplication? Or is duplication necessary?
L27, 45, 46: Would it make more sense to name it "dispensedBy" than "dispensedFrom", considering it references the user.
L59: JS-06: Avoid console.logs.
L64: JS-05: Avoid underscore.
L250 to L262: DE-01: Can we refactor to reduce duplication? Or is duplication necessary?

A future consideration would be some sort of implementation of an "Edit" button for the inventory items.

**Comment by guanhongl** [comment]
Dispense.jsx

---

architecture is good

design is good

JS
	L1: extra indent
	L40: ‘invenType’ variable name needs to be more descriptive
	L64: console log
	L89, 100, 180, 182: no inline style
	L172: ‘Form.Input’ can be made ‘Form.TextArea’
	
react is good

ui
	UI-01: ‘reason for dispense’ includes expired, broken, lost, etc. Maybe there should be a 
	separate page for reporting these issues?
	UI-02: grid could be stackable for responsiveness
	UI-04: not all fields provide example input
	UI-07: there are console errors

Status.jsx

---

architecture is good

design
	DE-03: lots of ‘dead’ code

JS
	L80, 87, 94: ‘limitOptions’, ‘brand’, ‘type’ should not be defined in render. Better to 
define in the constructor
	L87, 94: variable names need to be more descriptive
	L102, 112: no inline style
	L114, 151: Not sure if React.Fragment is appropriate here
	L117: Form.Group should not be used for a single Form.Field
	L119: Not sure what Popup is for
	
react
	RE-01: consider moving Table.Row to a subcomponent

ui
	UI-01: I think it’d be easier and intuitive to have a list w/ a ‘see more’ button instead of 
	pagination. 
Rows are missing some important columns (e.g. LotId, location). 
There should be an inventory type filter (e.g. medication, supplies) or maybe there could be separate tabs?
There should be a locations filter. Not sure if we need a brand filter.
	UI-02: page is not responsive
	UI-07: console errors

**Comment by len-nguyen** [comment]
Dispense.jsx

JS-06: Avoid console.logs.
JS-05: Avoid underscore.
UI-02: layout does not work on mobile 
UI-07: console errors due attribute being undefined

Status.jsx

DE-03: swal is not needed
JS-06: Avoid console.logs.
JS-05: Avoid underscore.
UI-02: layout does not work on mobile 
UI-07: console errors due to unused code
